name: pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5

      - name: Build (zbase)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/zetaoss/zbase:rc
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=zbase
          cache-to: type=gha,mode=max,scope=zbase

      - name: Build (zbase-dev)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: false
          build-args: |
            ZBASE_VERSION=rc
          tags: ghcr.io/zetaoss/zbase-dev:rc
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=zbase-dev
          cache-to: type=gha,mode=max,scope=zbase-dev
