name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  docker-push:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata (zbase)
        uses: docker/metadata-action@v5
        id: meta_zbase
        with:
          images: |
            ghcr.io/zetaoss/zbase
          tags: |
            type=ref,event=tag

      - name: Metadata (zbase-dev)
        uses: docker/metadata-action@v5
        id: meta_zbase_dev
        with:
          images: |
            ghcr.io/zetaoss/zbase-dev
          tags: |
            type=ref,event=tag

      - name: Build (zbase)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_zbase.outputs.tags }}
          labels: ${{ steps.meta_zbase.outputs.labels }}

      - name: Build (zbase-dev)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: true
          build-args: |
            ZBASE_VERSION=${{ github.ref_name }}
          tags: ${{ steps.meta_zbase_dev.outputs.tags }}
          labels: ${{ steps.meta_zbase_dev.outputs.labels }}
